### ISSUE TITLE
为什么每次训练只能30张，请问怎么修改

### ISSUE THREAD

**Issue by cuihua0** [dee1024/pytorch-captcha-recognition#17]
init net
epoch: 0 step: 3 loss: 0.2350926697254181
epoch: 1 step: 3 loss: 0.18072116374969482
epoch: 2 step: 3 loss: 0.14990365505218506
epoch: 3 step: 3 loss: 0.1484384387731552
epoch: 4 step: 3 loss: 0.12944868206977844
epoch: 5 step: 3 loss: 0.136171355843544
epoch: 6 step: 3 loss: 0.13556182384490967
epoch: 7 step: 3 loss: 0.1339406818151474
epoch: 8 step: 3 loss: 0.12743189930915833
epoch: 9 step: 3 loss: 0.12321759760379791
epoch: 10 step: 3 loss: 0.11995768547058105
epoch: 11 step: 3 loss: 0.12512315809726715
epoch: 12 step: 3 loss: 0.11607347428798676
epoch: 13 step: 3 loss: 0.1194273829460144
epoch: 14 step: 3 loss: 0.11752907186746597
epoch: 15 step: 3 loss: 0.11002203077077866
epoch: 16 step: 3 loss: 0.11969199776649475
epoch: 17 step: 3 loss: 0.11192518472671509
epoch: 18 step: 3 loss: 0.10305792093276978
epoch: 19 step: 3 loss: 0.10709385573863983
epoch: 20 step: 3 loss: 0.10055689513683319
epoch: 21 step: 3 loss: 0.09390119463205338
epoch: 22 step: 3 loss: 0.10000652819871902
epoch: 23 step: 3 loss: 0.08290736377239227
epoch: 24 step: 3 loss: 0.08297861367464066
epoch: 25 step: 3 loss: 0.07633257657289505
epoch: 26 step: 3 loss: 0.08562453091144562
epoch: 27 step: 3 loss: 0.06919705867767334
epoch: 28 step: 3 loss: 0.06607756018638611
epoch: 29 step: 3 loss: 0.07599730044603348
save last model

**Comment by cuihua0** [comment]
还是说这是固定的，我是py初学者，不是很懂

**Comment by asyncins** [comment]
> 还是说这是固定的，我是py初学者，不是很懂

在 my_dataset.py  文件中找到 get_train_data_loader() 方法，将方法中的 batch_size 改为你想要的数字即可。
