### ISSUE TITLE
模型成功率为0？

### ISSUE THREAD

**Issue by 245950258** [dee1024/pytorch-captcha-recognition#27]
使用captcha_gen.py脚本生成了1万张图片。然后直接使用captcha_train.py脚本，参数是num_epochs = 30
batch_size = 100
learning_rate = 0.001。
脚本执行完毕后使用test脚本，但是模型成功率为0.
请问，需要训练多少次才能达到0.96的正确率。

**Comment by zuxingshui** [comment]
我也想知道，求指导，谢谢

**Comment by Brycetlm** [comment]
我也是这样，，，请问解决了么

**Comment by 245950258** [comment]
没有，我后来选择别的验证码识别了。
